---
- name: Create /var/lib/kube-proxy
  file:
    path: /var/lib/kube-proxy
    state: directory
    mode: 0644

- name: Check if a kube-proxy exists
  stat:
    path: /usr/local/bin/kube-proxy
  register: kube_proxy_register

- name: Download kube-proxy
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/{{ arch }}64/kube-proxy
    dest: /usr/local/bin/
    mode: 0755
    owner: root
    group: root
  when: not kube_proxy_register.stat.exists

- name: Copy kubeconfig
  copy:
    src: ../../../files/kube-proxy.kubeconfig
    dest: /var/lib/kube-proxy/kubeconfig
    mode: 0644

- name: Configure kube-proxy-config.yaml
  template:
    src: kube-proxy-config.yaml
    dest: /var/lib/kube-proxy/kube-proxy-config.yaml

- name: Copy kube-proxy.service
  copy:
    src: kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service
    force: yes

- name: Run kube-proxy service
  systemd:
    name: kube-proxy
    state: restarted
    enabled: true
    daemon_reload: true
  register: result

- name: Gather service
  service_facts:

- name: Verify kube-proxy service
  fail:
    msg: 'kube-proxy is not running!!!'
  when: ansible_facts["services"]["kube-proxy.service"].state != "running"
