---
- name: Create k8s cluster
  #hosts: k8s_master
  hosts: local
  become: true
  roles:
    - role: etcd
      tags:
        - etcd
    - role: kube-apiserver
      tags:
        - kube-apiserver

