---
- name: Install required packages
  apt:
    update_cache: "yes"
    install_recommends: "no"
    name:
      - unzip

- name: Upgrade packages
  apt:
    update_cache: "yes"
    upgrade: "yes"
    install_recommends: "no"

- name: Clean
  apt:
    autoclean: "yes"
    autoremove: "yes"
