---
- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
  loop:
    - /etc/etcd
    - /var/lib/etcd

- name: Deploy binaries
  unarchive:
    src: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-{{ arch }}64.tar.gz"
    dest: /usr/local/bin/
    mode: "0755"
    owner: root
    group: root
    remote_src: "yes"
    extra_opts:
      - -z
      - --strip-components=1
      - etcd-v{{ etcd_version }}-linux-{{ arch }}64/etcd
      - etcd-v{{ etcd_version }}-linux-{{ arch }}64/etcdctl

- name: Deploy certificates and private keys
  copy:
    src: "{{ item }}"
    dest: /etc/etcd/
    mode: "0600"
  loop:
    - ../../../files/certificates/etcd-ca.pem
    - ../../../files/certificates/etcd-ca-key.pem
    - ../../../files/certificates/kube-etcd.pem
    - ../../../files/certificates/kube-etcd-key.pem
    - ../../../files/certificates/kube-etcd-peer.pem
    - ../../../files/certificates/kube-etcd-peer-key.pem
    - ../../../files/certificates/kube-etcd-healthcheck-client.pem
    - ../../../files/certificates/kube-etcd-healthcheck-client-key.pem

- name: Deploy a unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: "0755"

- name: Restart etcd
  systemd:
    name: etcd
    state: restarted
    enabled: true
    daemon_reload: true
  register: result
  failed_when: not result.state == "started"
