---
- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
  loop:
    - /var/lib/kubernetes
    - /etc/kubernetes/config

- name: Deploy kube-scheduler
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/{{ arch }}/kube-scheduler"
    dest: /usr/local/bin/kube-scheduler
    mode: "0755"

- name: Deploy a kubeconfig file
  copy:
    src: ../../../files/kubeconfigs/kube-scheduler.kubeconfig
    dest: /var/lib/kubernetes/kube-scheduler.kubeconfig
    mode: "0600"

- name: Deploy a kube-scheduler configuration file
  copy:
    src: kube-scheduler.yaml
    dest: /etc/kubernetes/config/kube-scheduler.yaml
    mode: "0744"

- name: Deploy a unit file
  copy:
    src: kube-scheduler.service
    dest: /etc/systemd/system/kube-scheduler.service
    mode: "0755"

- name: Restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    enabled: true
    daemon_reload: true
  register: result
  failed_when: not result.state == "started"
